export PROXY_PORT=80
export PROXY_HOST="0.0.0.0"
export BACKEND_PORT=3000
export BACKEND_HOST="192.168.1.201"
docker run -d -e PROXY_PORT=$PROXY_PORT -e BACKEND_PORT=$BACKEND_PORT -e PROXY_HOST=$PROXY_HOST -e BACKEND_HOST=$BACKEND_HOST -p $PROXY_PORT:$PROXY_PORT "$1" sh /app/start.sh
